### ISSUE TITLE
Ufo siger at pid: 870970-basis:52963559 er ugyldig - deuden  faust og isbn

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/dbc-ufo#115]
pid findens i brønd 3.0 og brønd 3.5 og er indekseret:

SOLR:
http://cisterne-solr.dbc.dk:8983/solr/cisterne-corepo-20161124/select?indent=on&q=fedoraPid:%22870970-basis:52963559%22&wt=json

Corepo:

http://introspect.corepo.cisterne.mcp1.dbc.dk/?tab=Search&header=pid&header=title&query=870970-basis:52963559&limit=20

**Comment by kkdbc** [comment]
![9788799236244](https://cloud.githubusercontent.com/assets/18323273/24100327/fef24c08-0d73-11e7-81c3-e7f0463b34e3.jpg)

**Comment by KiraH** [comment]
testet OK
