### ISSUE TITLE
Uploadet billede kan ikke ses i grænseflade

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/dbc-ufo#132]
Henvendelse fra Færøerne ang. uploadet billede som ikke kan ses i deres lokale grænseflade eller bibliotek.dk. Billedet er uploadet ca. 5. maj.
Lokal visning: https://www.bbs.fo/web/arena/results?p_r_p_687834046_search_item_id=90376675
Bibliotek.dk: http://bibliotek.dk/linkme.php?rec.id=820010-katalog%3A6292807

Billedet findes i moreinfo ved request til servicen (v2.6) på isbn, men ikke på lokal identifier (faustnr fra bibdk url) - kan det være problemet? Lokal identifier indeholder kun 7 cifre, som det ses i bibdk linket ovenfor
Ved ikke om bibliotek.dk spørger vha faust/pid/isbn.

<mi:moreInfoRequest xmlns:mi="http://oss.dbc.dk/ns/moreinfo">
		<mi:authentication>
				<mi:authenticationUser>xxx</mi:authenticationUser>
				<mi:authenticationGroup>yyy</mi:authenticationGroup>
				<mi:authenticationPassword>zzz</mi:authenticationPassword>
		</mi:authentication>
		<mi:identifier>
				<mi:isbn>9789997212184</mi:isbn>
		</mi:identifier>
</mi:moreInfoRequest>

**Comment by vibjerg** [comment]
Billedet er ikke uploadet til 820010-katalog:6292807 men til 125610-katalog:90376675, og billedet kan søges frem i moreinfo med følgende identifier:

```xml
<mi:identifier>
<mi:localIdentifier>90376675</mi:localIdentifier>
<mi:libraryCode>125610</mi:libraryCode>
</mi:identifier>
```
Men den fremkommer ikke når man benytter 

```xml
<mi:identifier>
   <mi:pidList>125610-katalog:90376675</mi:pidList>
</mi:identifier>
```

Det bør den gøre. Jeg undersøger nærmere.

**Comment by vibjerg** [comment]
Fejlen skyldes en forkert søgeprofil, så billedet er blevet koblet på 125610-katalog:90376675 i stedet for 820010-katalog:6292807. Søgeprofilen på UFO benytter nu bibliotek.dk profilen , og billedet er 16.Maj uploadet igen.

**Comment by vibjerg** [comment]
Der er nu kommet et billede på https://bibliotek.dk/da/work/820010-katalog%3A6292807
