### ISSUE TITLE
ufo jobbet ofte i rødt

### ISSUE THREAD

**Issue by KiraH** [DBCDK/dbc-ufo#135]
Ufo jobbet går ofte i rødt pga fejl i selenium tests.

Det kunne være rart at kigge nærmere på hvorfor så vi er sikre på vi har et job der virker som det skal.

**Comment by fvsdbc** [comment]
Selenium testene giver vekslende resultat fra gang til gang. På Travis kan man få det til at blive grønt ved at køre det en del gange. På IS'en kører det gult eller rødt. Oftest brokker den sig over et alert vidue som enten skal være der eller ikke må være det, man andre fejl ses også. Lokalt kører testene igennem. På IS'en slås selenium testene fra.

**Comment by KiraH** [comment]
Jeg åbner denne igen, så vi ikke glemmer den. Selenium nu slået fra på isen men køres af udviklerne på travis. 

Vi genbesøger denne senere og ser om vi ikke kan få det til at køre på isen også.

**Comment by KiraH** [comment]
Det virker nu.
