### ISSUE TITLE
Infotekst om at billeder ikke kan ses med det samme

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/dbc-ufo#156]
https://ufo.dbc.dk/help skal tilføjes en sætning om at der er en forsinkelse på fra man loader til billederne reelt ligger der hvor de kan udleveres til grænsefladerne.

Evt:
Note: De uploadede forsider er IKKE synlige med det samme i biblioteksgrænsefladerne.  Der kan gå op til 24 timer før dette sker.

**Comment by BettinaAndersen** [comment]
Derudover har vi haft en kundesag med besked om at der på siden står at 
"Når man uploader forsider til UFO, skal størrelsen være mindst 500x500px", men ifølge brugeren afvises, hvis de ikke er mindst 501x501px. Det bør rettes sammen med denne rettelse, hvis det er tilfældet.

**Comment by fvsdbc** [comment]
Fixed

**Comment by KiraH** [comment]
testet OK
