### ISSUE TITLE
Upload af forsider til lokalposter

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/dbc-ufo#157]
Fx for det færøske bibliotek 911116, post med id: 125775667

**Comment by fvsdbc** [comment]
Funker på staging hvor id'et findes og billedet oploades og sukker op i databasen dagen efter - og kan findes med moreinfo staging. (ufo staging bruger den åbne platform og i den opsætning er openSeach og moreInfo driftversionerne, så  ufo staging finder ikke billedet næste dag og advarer om at det findes.

**Comment by KiraH** [comment]
testet OK
