### ISSUE TITLE
Integrationstests skal køres på CI miljøet (ux-is.dbc.dk)

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/dbc-ufo#37]

**Comment by hrmoller** [comment]
IS'en smider en `Error: EXDEV: cross-device link not permitted, rename ...` ved afvikling af integrationstests på ux-is. Det skyldes sandsynligvis at et billede uploades og derefter flyttes fra een partition til en anden hvilket NPM ikke kan lide.

Se .feks. her: https://github.com/npm/npm/issues/13306 og her http://stackoverflow.com/questions/37153666/error-exdev-cross-device-link-not-permitted-rename-tmp-on-ubuntu-16-04-lts

**Comment by vibjerg** [comment]
Bliver løst med #8

**Comment by KiraH** [comment]
Er ikke løst, de fejler stadig.

**Comment by vibjerg** [comment]
Testene kan nu afvikles på jenkins.
